[package]
name = "clast"
version = "1.0.0"
edition = "2024"

[dependencies]
bytes = { version = "1.11.0", optional = true }

[build-dependencies]
rand_chacha = "0.9.0"

[features]
default = ["fastcdc"]
fastcdc = ["bytes"]
